conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
#urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('policy/', views.policy, name='policy'),
    path('term/', views.term, name='term'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),

]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
#forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
#views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from django.contrib.auth import logout

from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def logout_view(request):
    logout(request)
    return render(request, 'core/logout.html')

def contact(request):
    return render(request, 'core/contact.html')

def about(request):
    return render(request, 'core/about.html')

def policy(request):
    return render(request, 'core/policy.html')

def term(request):
    return render(request, 'core/term.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

core/templates/core/about.html
{% extends 'core/base.html' %} 

{% block title %}About{% endblock %} 

{% block content %}
    <body class="bg-gray-100">
        <div class="container mx-auto mt-8 px-4">
            <h1 class="text-3xl font-semibold text-center mb-6">About Us</h1>
            <p class="text-lg text-gray-700 mb-8">Welcome to our online marketplace! We're dedicated to providing a seamless shopping experience for our customers and connecting them with a diverse range of products and sellers.</p>
            <p class="text-lg text-gray-700 mb-8">At Puddle, we believe in the power of community and collaboration. Our platform brings together buyers and sellers from around the world, creating a vibrant marketplace where everyone can find what they're looking for.</p>
            <p class="text-lg text-gray-700 mb-8">Thank you and We're excited to embark on this journey with you and create a thriving community of buyers and sellers. Happy shopping!</p>
        </div>
    </body>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Puddle</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Puddle</a>

            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                
                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a> 
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>                    
                {% endif %}

                {% if user.is_authenticated %}
                <a href="{% url 'core:logout' %}">Logout</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Welcome to Puddle website, we believe in the power of community and collaboration.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'core:about' %}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="{% url 'core:policy' %}" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="{% url 'core:term' %}" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %} 

{% block title %}Contact{% endblock %} 

{% block content %}
    <body class="bg-gray-100">
        <div class="container mx-auto mt-8 px-4">
            <h1 class="text-3xl font-semibold text-center mb-6">Contact Us</h1>
            <p class="text-lg text-gray-700 text-center mb-8">Have a question or feedback? Feel free to get in touch with us using the form below.</p>
            <form action="#" method="post" class="max-w-md mx-auto">
                <div class="mb-4">
                    <label for="name" class="block text-gray-700">Your Name:</label>
                    <input type="text" id="name" name="name" class="w-full px-4 py-2 rounded-lg border-gray-300 focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50" required>
                </div>
                <div class="mb-4">
                    <label for="email" class="block text-gray-700">Your Email:</label>
                    <input type="email" id="email" name="email" class="w-full px-4 py-2 rounded-lg border-gray-300 focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50" required>
                </div>
                <div class="mb-4">
                    <label for="message" class="block text-gray-700">Message:</label>
                    <textarea id="message" name="message" class="w-full px-4 py-2 rounded-lg border-gray-300 focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50" rows="5" required></textarea>
                </div>
                <button type="submit" class="bg-teal-500 text-white px-4 py-2 rounded-lg hover:bg-teal-600 focus:outline-none focus:bg-blue-600">Send Message</button>
            </form>
        </div>
    </body>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}


        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>
        
        {% if form.error or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
            
        
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Logout</h1>

    <p>You have been successfully logged out.</p>
</div>
{% endblock %}

core/templates/core/policy.html
{% extends 'core/base.html' %} 

{% block title %}Contact{% endblock %} 

{% block content %}
    <body class="bg-gray-100">
        <div class="container mx-auto mt-8 px-4">
            <h1 class="text-3xl font-semibold text-center mb-6">Privacy Policy</h1>
            <p class="text-sm text-gray-700 mb-8">At Puddle, we take your privacy seriously. This privacy policy outlines how we collect, use, and protect your personal information when you use our website or mobile app.</p>
            <h2 class="text-xl font-semibold mb-4">Information We Collect</h2>
            <p class="text-sm text-gray-700 mb-8">We may collect personal information such as your name, email address, shipping address, and payment details when you create an account, make a purchase, or interact with our platform.</p>
            <h2 class="text-xl font-semibold mb-4">How We Use Your Information</h2>
            <p class="text-sm text-gray-700 mb-8">We use your personal information to process orders, communicate with you about your account, provide customer support, and improve our services. We may also use your information for marketing purposes, such as sending promotional emails or personalized recommendations.</p>
            <h2 class="text-xl font-semibold mb-4">Third-Party Links</h2>
            <p class="text-sm text-gray-700 mb-8">Our website or app may contain links to third-party websites or services that are not operated by us. We have no control over the content, privacy policies, or practices of these websites or services and are not responsible for their actions.</p>
            <p class="text-sm text-gray-700 mb-8">By using our website or app, you consent to the terms of this privacy policy. We may update this policy from time to time, and any changes will be posted on this page.</p>
            <p class="text-sm text-gray-700 mb-8">If you have any questions or concerns about our privacy policy, please contact us via the contact page.</p>
        </div>
    </body>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label><br>
            {{ form.password2 }}
        </div>

        
        {% if form.error or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
            
        
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/term.html
{% extends 'core/base.html' %} 

{% block title %}Contact{% endblock %} 

{% block content %}
    <body class="bg-gray-100">
        <div class="container mx-auto mt-8 px-4">
            <h1 class="text-3xl font-semibold text-center mb-6">Terms of Use</h1>
            <p class="text-sm text-gray-700 mb-8">Welcome to Puddle! By using our website, you agree to comply with these terms of use. Please read them carefully before accessing or using our platform.</p>
            <h2 class="text-md font-semibold mb-4">User Conduct</h2>
            <p class="text-sm text-gray-700 mb-8">You agree to use our platform for lawful purposes and in compliance with all applicable laws and regulations. You may not use our platform to engage in any illegal activities, violate the rights of others, or transmit harmful or objectionable content.</p>
            <h2 class="text-md font-semibold mb-4">Intellectual Property</h2>
            <p class="text-sm text-gray-700 mb-8">All content on our platform, including text, graphics, logos, and images, is the property of [Your Marketplace Name] and is protected by copyright and other intellectual property laws. You may not use, reproduce, or distribute any content from our platform without our prior written consent.</p>
            <h2 class="text-md font-semibold mb-4">Disclaimer of Warranties</h2>
            <p class="text-sm text-gray-700 mb-8">Our platform is provided on an "as is" and "as available" basis, without any warranties of any kind, express or implied. We do not guarantee the accuracy, reliability, or completeness of any content on our platform, and we disclaim all liability for any errors or omissions.</p>
            <h2 class="text-md font-semibold mb-4">Limitation of Liability</h2>
            <p class="text-sm text-gray-700 mb-8">In no event shall Puddle be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of our platform, whether based on warranty, contract, tort, or any other legal theory, even if we have been advised of the possibility of such damages.</p>
            <p class="text-sm text-gray-700 mb-8">If you have any questions or concerns about our terms of use, please contact us via the contact page.</p>
        </div>
    </body>
{% endblock %}